USE [REPORTS]
GO

/****** Object:  Table [dbo].[O_NAKL_ARC]    Script Date: 24.08.2020 12:56:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[O_NAKL_ARC](
	[RECNO] [int] IDENTITY(1,1) NOT NULL,
	[UNICUM_NUM] [int] NOT NULL,
	[NUM_DOC] [int] NOT NULL,
	[DATE_DOC] [smalldatetime] NULL,
	[SUM_DOC] [float] NULL,
	[DRIVER] [varchar](40) NULL,
	[CAR_UID] [int] NULL,
	[TYPE_DOC] [varchar](20) NULL,
	[OTMETKA] [bit] NULL,
	[FAMILY] [varchar](10) NULL,
	[CREATE_DATE] [smalldatetime] NULL,
	[WHO_CORR] [varchar](10) NULL,
	[CORR_DATE] [smalldatetime] NULL,
	[PRIMECH] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[RECNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[O_NAKL_ARC] ADD  DEFAULT ((0)) FOR [SUM_DOC]
GO

ALTER TABLE [dbo].[O_NAKL_ARC] ADD  DEFAULT ((0)) FOR [OTMETKA]
GO

ALTER TABLE [dbo].[O_NAKL_ARC] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO


