CREATE TABLE O_DRIVERS (UID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
						Family varchar(35) Not Null,
						Name varchar(15) Not Null,
						LastName varchar(40) Null,
						BirthDay date Null,
						Pass_Serial varchar(10) Null,
						Pass_Num varchar(6) Null,
						License_Serial varchar(6) Null,
						License_Num varchar(10),
						License_BegDate date Null,
						License_EndDate date Null,
						License_Gave varchar(50) Null,
						License_Access varchar(30) Null,
						Adress varchar(150) Null,
						UID_Car int Null,
						Date_Hiring smalldatetime DEFAULT GETDATE(),
						Available bit DEFAULT 0,
						Primech varchar(250) Null,
						CONSTRAINT FK_UidCar FOREIGN KEY (UID_Car) REFERENCES CARS_INSURANCE(UID) ON DELETE SET NULL)